# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff'),
        ),
    ]
