# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20171112_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_id',
            field=models.TextField(default='<django.db.models.fields.DateField>-<built-in function id>', primary_key=True, serialize=False),
        ),
    ]
