# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_receipt_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
