# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171109_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
