# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171109_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
