# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171110_0029'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='workplaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
