# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171110_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='workplace',
        ),
    ]
