# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company'),
        ('accounts', '0016_remove_staff_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company'),
        ),
    ]
