# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staff_workplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='workplace',
            new_name='workplaces',
        ),
    ]
