# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20171110_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='workplaces',
            field=models.ManyToManyField(related_name='workplace_of_staff', to='companies.Company'),
        ),
    ]
