# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_staff_workplace'),
        ('companies', '0003_auto_20171110_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
