# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20171113_1542'),
        ('companies', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(related_name='staff_in_company', to='accounts.Staff'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_company', to='accounts.Staff'),
        ),
    ]
