# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
