# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20171110_0333'),
        ('salary', '0006_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_upload_salary', to='accounts.Staff'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_get_salary', to='accounts.Staff'),
        ),
    ]
