# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_auto_20171113_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_upload_salary', to='accounts.Staff'),
        ),
    ]
