# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0011_auto_20171113_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_who_pay_others', to='accounts.Staff'),
        ),
    ]
