# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.Salary')),
            ],
        ),
    ]
