# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 06:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
