# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20171107_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
